name: Verify
on:
  pull_request:
    branches:
      - master
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Check node_modules
        run: ls -la node_modules
      - name: Build
        run: yarn packasso build
      - name: Test
        run: yarn packasso test
