name: Verify
on:
  pull_request:
    branches:
      - master
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn self:build
      - name: Test
        run: yarn test
